environment:

  # SDK v7.0 MSVC Express 2008's SetEnv.cmd script will fail if the
  # /E:ON and /V:ON options are not enabled in the batch script intepreter
  # See: http://stackoverflow.com/a/13751649/163740
  CMD_IN_ENV: "cmd /E:ON /V:ON /C obvci_appveyor_python_build_env.cmd"

  matrix:
    - TARGET_ARCH: x64
      CONDA_PY: 27
      CONDA_INSTALL_LOCN: C:\\Miniconda-x64


# We always use a 64-bit machine, but can build x86 distributions
# with the TARGET_ARCH variable.
platform:
    - x64

install:
    - cmd: set
    # Cywing's git breaks conda-build. (See https://github.com/conda-forge/conda-smithy-feedstock/pull/2.)
    - cmd: rmdir C:\cygwin /s /q

    # Add path, activate `conda` and update conda.
    - cmd: call %CONDA_INSTALL_LOCN%\Scripts\activate.bat

    - cmd: set PYTHONUNBUFFERED=1

    # Add our channels.
    - cmd: conda config --set show_channel_urls true
    - cmd: conda config --add channels conda-forge
    - cmd: conda config --add channels gorgoncryoem/label/dependency
    - cmd: conda config --add channels shadow_walker/label/dev

    # Configure the VM.
    - cmd: set CPU_COUNT=2
    - cmd: conda install --quiet --yes obvious-ci
    - cmd: conda config --set add_pip_as_python_dependency false
    - cmd: conda install -n root --yes --quiet vs2008_express_vc_python_patch
    - cmd: call setup_x64
    - cmd: conda install --yes --quiet qt=4 pyqt=4
    - cmd: conda install --yes --quiet -c conda-forge boost boost-cpp fftw
    - cmd: conda install --yes --quiet -c jmbell ftgl
    - cmd: conda install --yes --quiet freetype gsl hdf5 ipython jpeg libpng libtiff matplotlib numpy=1.11 pyopengl scikit-learn scipy theano tk cmake
    - cmd: conda info
    - cmd: conda config --get


# Skip .NET project specific build phase.
build: off

test_script:
    # Update to latest `conda`, because earlier versions fail to download from ftp
    - "%CMD_IN_ENV% conda update --yes --quiet conda -c defaults"
    # Only download szip source
    - "%CMD_IN_ENV% conda build %APPVEYOR_BUILD_FOLDER%\\recipes\\szip --source --quiet"
    # Install conda-build-all,
    # this may pull older version of conda,
    # but since szip is in the cache, it should skip the download during build
    - "%CMD_IN_ENV% conda install --yes --quiet conda-build-all"
    - "%CMD_IN_ENV% conda-build-all %APPVEYOR_BUILD_FOLDER%\\recipes --matrix-conditions python 2.7.*"
